export default {
    lineColor: 'L',
    lineColorFull: 'צבע קו',
    fillColor: 'F',
    fillColorFull: 'צבע מילוי',
    alpha: 'A',
    alphaFull: 'Alpha',
    lineWidth: 'W',
    lineWidthFull: 'Line width',
    arrowLength: 'L',
    arrowLengthFull: 'Arrow length',
    eraserWidth: 'E',
    eraserWidthFull: 'Eraser width',
    textColor: 'C',
    textColorFull: 'Text color',
    fontSize: 'S',
    fontSizeFull: 'Font size',
    fontStrokeSize: 'St',
    fontStrokeSizeFull: 'Stroke width',
    fontStyle: 'FS',
    fontStyleFull: 'Font style',
    fontName: 'F',
    fontNameFull: 'Font name',
    textStrokeColor: 'SC',
    textStrokeColorFull: 'Stroke color',
    apply: 'Apply',
    cancel: 'Cancel',
    close: 'Close',
    clear: 'Clear',
    width: 'Width',
    height: 'Height',
    keepRatio: 'Keep width/height ratio',
    fillPageWith: 'Fill page with current background color',
    pixelSize: 'P',
    pixelSizeFull: 'Pixel size',
    resizeScale: 'Scale',
    resizeResize: 'Resize',
    backgroundColor: 'Page background color',
    pixelizePixelSize: 'Pixelize pixel size',
    language: 'Language',
    wrongPixelSizeValue:
        'Wrong pixel size. You can enter e.g. \'20%\' which mean pixel size will be 1/5 of ' +
        'the selected area side, or \'4\' means 4 px',
    tools: {
        crop: 'חיתוך',
        pixelize: 'Pixelize selected area',
        rect: 'צייר מלבן',
        ellipse: 'צייר אליפסה',
        line: 'מתח קו',
        arrow: 'מתח חץ',
        rotate: 'סבב 180 מעלות',
        rotateR: 'סבב ימינה',
        rotateL: 'סבב שמאלה',
        save: 'שמירה',
        load: 'Load image',
        text: 'תיבת טקסט',
        brush: 'מברשת',
        resize: 'Resize or scale',
        open: 'Open image',
        select: 'Select area',
        close: 'Close Painterro',
        eraser: 'Eraser',
        settings: 'Settings',
        undo: 'ביטול',
        redo: 'Redo',
        print: 'הדפסה',
        measure: 'סרגל מדידה'
    },
    pasteOptions: {
        fit: 'Replace all',
        extend_down: 'Extend down',
        extend_right: 'Extend right',
        over: 'Paste over',
        how_to_paste: 'How to paste?',
    },
};
